CREATE TABLE "GAB_5120_AP_OITEMDT"(
 "INVOICE" CHAR(15),
 "DATE_INVOICE" DATE,
 "DATE_DUE_ORIGINAL" DATE,
 "DATE_DUE_NEW" DATE);

CREATE TABLE "GAB_5120_AR_OITEMDT"(
 "INVOICE" CHAR(7),
 "DATE_INVOICE" DATE,
 "DATE_DUE_ORIGINAL" DATE,
 "DATE_DUE_NEW" DATE);
